### ISSUE TITLE
Example with server side sorting, filtering, grouping, and pagination...

### ISSUE THREAD

**Issue by zam6ak** [esvit/ng-table#242]
I am aware of "AJAX Data Loading" example on the website, but it appears all of other examples regarding data sorting, filtering, grouping, and pagination are occurring client side (browser).

Is there an example of performing this on server side?
I guess what I am really interested in is an example on how to format, serialize, and send parameters (sort, filter, page, size) to a resource (or Restangular or...)...

Thanks!

**Comment by zvaraondrej** [comment]
+1

**Comment by Phebonacci** [comment]
I know it's a bit late but someone did a really good example of displaying server-side sorted data:
https://www.codeproject.com/Articles/892301/Server-side-Data-Filtering-Sorting-and-Paging-with

I didn't know we could do this. This isn't so clear in the documentation. :(

**Comment by rbhargava25** [comment]
Hi foxdonut ,
You comment really help full, But as I am new few things are not clear to me 
1#  Why receiveData is being passed as a argument into a function.
When I am calling my ajax function instead of 
MyResource.query(queryParams, receiveData);
it is showing data but as ajax returns later then count is not being refreshed. And if I am using reload inside the ajax code then it goes into infinte loop :(

**Comment by foxdonut** [comment]
Hi @rbhargava25 

> Why receiveData is being passed as a argument into a function.

Because `MyResource.query` is an asynchronous function. It is making a request to the server, and when the response comes back, we need to know what code to execute. In this case, it is to call the _callback function_, which is `receiveData`.

Hope that helps.

**Comment by rbhargava25** [comment]
Great thanks Foxdonut... 
I will using simple http request instead of Resource I am hopping that it will work.
