### ISSUE TITLE
when the user is filtering and the tableParams.page selected is higher than filter result page, it sound that have no result found

### ISSUE THREAD

**Issue by adansklevanskis** [esvit/ng-table#250]
when the user is filtering and the tableParams.page selected is higher than filter result page, it sound that have no result foun
![erro](https://f.cloud.github.com/assets/5330124/2465878/fdbeabec-afa7-11e3-9b02-aea3c525ee98.png)
d

**Comment by QuentinFchx** [comment]
@ccrowhurstram Do you think we could add a fix for cases like this ?
I also ran into this issue.
Whenever we reload the page, we could check if the current pagination `count * page` is not above the total and set the page to the last (or first ?) one ?

**Comment by ccrowhurstram** [comment]
**I believe the problem was fixed a long time ago** by the following commit:

https://github.com/esvit/ng-table/commit/194beb677167f7005c8d03b9b8922c554d754724#diff-6de4ed9638645794656227bd610ea214R37

Basically, any time the filter changes, a $watch is triggered which will reset the current page to 1 *before* the `reload` method of the grid is executed.

The problem is the examples on the doc site (http://bazalt-cms.com/ng-table/) are using an *old version of the code prior to the above change*.

I have also checked my assumption by writing a test to prove the behaviour: https://github.com/esvit/ng-table/commit/2705b946a6110cfe3bcfd5c5e3598f8bf0b5c4ee#diff-5caab3ad7068a0eb1dd75e825b733537R322

**Comment by QuentinFchx** [comment]
Indeed, I was not using `params.filter` but I was just calling `.reload()` on the table.
I fixed this on my side, thanks for pointing this out :)
