### ISSUE TITLE
isNumber function in ngTableParams factory

### ISSUE THREAD

**Issue by graphicsxp** [esvit/ng-table#33]
I've come across an issue with the filter feature. If I type 001 for the filter criteria, it is kept as a string, which is what I want. Then I click on next page and the filter criteria is converted to a number and becomes 1 instead of 001. 

This is because in the ngTableParams factory, you have this bit of code that checks the type of data[key] : 

```
     this[key] = (isNumber(data[key]) ? parseFloat(data[key]) : data[key]);
```

"001" is successfully converted to a number, but that's not what I want.  If I get rid of that, it works fine, but I'm not sure about the consequences this could have.

What is the reason for this code in the first place ?

**Comment by tzsolti** [comment]
The problem is deeper than that. Lets say you want to filter a string which contains only numbers, ex. 

198734758347573897593479573495793475937495374985734985

Because the isNumber thinks that this is a number, the parseFloat will transform this into 

1.987347583475739e+53

which of course is really different from the original string.
