### ISSUE TITLE
multi-level or nested grouping

### ISSUE THREAD

**Issue by nabeelahm2** [esvit/ng-table#615]
Hi,

Just wondering is there any plan to add  multi-level or nested grouping features in any of upcoming releases?.

**Comment by christianacca** [comment]
Hi @nabeelahm2, I'm not really sure how useful the grouping functionality is anyway as currently implemented.

Take for example the demo: http://ng-table.com/#/demo/4-1

For me it doesn't make sense that the list of user's are split between page 1 and 2 of the grid.

Instead of using the grouping feature of ngtable, I would probably shape the data to be displayed in the grid already grouped. For example:

```` javascript
{
  name: "Christian",
  children: [{ name: "xx" }, { name: "yy" }]
}
````

In the html for my table I would then use a *nested table* to render the children. That nested table would not require the ng-table directive.

Note: I haven't tried the above so I might be talking rubbish!
