### ISSUE TITLE
I cannot translate table title with gettext

### ISSUE THREAD

**Issue by burakkilic** [esvit/ng-table#695]
Hi;

I want to translate tables titles with gettext angular.

    <td data-title="'Name'" class="col-md-3"> 

becomes 

    <td data-title="{{'Name'|translate}}" class="col-md-3">

But it gives following error:

    Syntax Error: Token '{' invalid key at column 2 of the expression [{{'Name'|translate}}] starting at [{'Name'|translate}}].

How can I fix that?

**Comment by christianacca** [comment]
The problem here is that data-title accepts an expression not an interpolated string.

What you'll need to do is use the translate filter inside a function inside your controller. Something like:

```html
<td data-title="ctrl.translate('Name')" class="col-md-3">
```

See this [codepen](http://codepen.io/christianacca/pen/ojXYxE?editors=101) for an worked example.

Specifically see the following html markup:

```html
<td title="demo.translate('Admin Email')" filter="{adminEmail: 'text'}" sortable="'adminEmail'">{{row.adminEmail}} </td>
```

**Comment by burakkilic** [comment]
We solve this with data-title="'Sender' | translate"

No need to curly brackets.

Thank you.

**Comment by AlexandrAnash** [comment]
hi, 
tell me what if I have a ng-table-dynamic
ng-table-dynamic="table.tableParams with settingTable"

$scope.settingTable = [
    { title: " 'foo' | translate", field: "id", filter: { id : "text" }, show: true, sortable: "id" }, 
    { title: " 'bar' | translate", field: "installationAt" },
    ...
];
How me in this case to translate?
