### ISSUE TITLE
Default close after change group

### ISSUE THREAD

**Issue by lichtner** [esvit/ng-table#744]
It is possible set via options default closing after change group?

**Comment by christianacca** [comment]
There's no option for that. 

You should be able to add it simply to your *own* table html / controller. You would create a `toggleGroup` method in your own controller that takes the current group clicked on and set the `$hideRows` of other groups in $groups to false.

**Comment by lichtner** [comment]
I am not sure if I understand you. My question was: I would like to change grouping column (so I click in header of table, not in rows of data). E.g. I have list of users and permissions and I want to change grouping by users to grouping by permissions. Is it possible close "column selector" in table header after changing grouping column? Could you give me small example?

**Comment by christianacca** [comment]
I see. I intentionally kept the group picker open. The reason being is that you can select the group again and it will change the sort order for that group.

I think the root cause is that the UI for the group picker should be improved to make the picking of a new group separate from selecting the sort order for a group. Then it would make sense to close the picker as soon as a new group column was selected.

**Comment by lichtner** [comment]
yes I agree. :+1: 
thanks for your work, ngTable is best angular grid for me.
