### ISSUE TITLE
Feature requests - What I think is needed before v1.0

### ISSUE THREAD

**Issue by AmitMY** [esvit/ng-table#772]
Hello!
I really like this table, and think everyone should use it, but before, there are 3 major things that are needed. {orderBy: 'importance'}

1) Floating header - showing a big table without a floating header is just wrongs. I have tried multiple times to do it myself, but with no success.

2) Fixed columns - if our table is big, we usually want to save the most important columns on the left.
(example, user data: id, name, skype, facebook, twitter, icq, github, stackoverflow should hold the 2 first columns: id, name)
_EDIT_
Well, I found something that does this on normal tables, so it must be possible: http://zurb.com/playground/playground/responsive-tables/index.html

3) Floating Tfoot - as hard as a floating header, but realy aint as needed.

I have created lots of code around this table, and added so many options! I wait for a stable 1.0 to start and incorporate all of my features in it.

Hopefully someone knows how to make a floating header, and the fixed columns, for it will give me a lot of relief at work, and a greater will to invest in it :)

**Comment by thanhlq** [comment]
+1

**Comment by okamiconcept** [comment]
I think this possibilities are not possible in its current implementation, because of the table dom elements and its fixed positions.

The others implementation like ui-grid (http://ui-grid.info) made the choice to construct their grid on div elements, which can make then float or contains columns with overflow etc.

Il like the table approach, that's why i prefer ngTable, but if you want those, you have to rewrite all the library :) or simply change to ui-grid or other.

I think it's possible, by creating an absolute positionning div above but it would be a bit crappy ...

**Comment by AmitMY** [comment]
I opt to ng-table for the same reason - it is a table!
But for your information, if you change the tbody to display:block, and then make the thead position fixed or something, it is floating. But it wont get the table column sizes of the table, so you have to go over the table and change the thead's cells to be in the right width.
IT IS CLUNKY, therefore I concluded it as a fail. (widths often become weird)
This covers 1,3

For 2 - fixed columns - I agree. It is impossible (or very hard) to do it on a table, but I am no master of code so I cant make that judgement call.
