### ISSUE TITLE
select filter with option that is substring of another

### ISSUE THREAD

**Issue by nogap** [esvit/ng-table#793]
Hi
In the select demo: http://ng-table.com/#/filtering/demo-select
if you select 'United States' you also get results of 'United States Minor Outlying Islands'.
I'm using 1.0.0-beta.8

**Comment by alonsegal** [comment]
This is because the default filter comparator behavior of AngularJS filters (See here: [).](https://docs.angularjs.org/api/ng/filter/filter)
You should simply override that in the NgTableParams. There you have filterOptions.filterComparator .

(Maybe it is also a good enhancement to change the "defaultFilterOptions" when using  select filter).

**Comment by tyronedougherty** [comment]
@alonsegal (or anyone else) is it possible to use the filterCompator on only a single column? I have a table with a variety of filters, only one of which is a select filter. I would only like an exact match filter on the select filter, while leaving the text filters with unexact matches.

I can't find anything that doesn't override all of the filters using something like this:
```
this.tableParams = new NgTableParams({}, {
      filterOptions: { filterComparator: true }
    });
```

Meaning it would break my other filters. Is it possible to do this?
